(defun insert-line-below ()
  "Insert an empty line below current line."
  (interactive)
  (end-of-line)
  (open-line 1)
  (next-line 1)
  (indent-according-to-mode))
(defun insert-line-above ()
  "Insert an empty line above current line."
  (interactive)
  (end-of-line 0)
  (open-line 1)
  (next-line 1)
  (indent-according-to-mode))
(defun move-line-up ()
  "Move up the current line."
  (interactive)
  (transpose-lines 1)
  (forward-line -2)
  (indent-according-to-mode))
(defun move-line-down ()
  "Move down the current line."
  (interactive)
  (forward-line 1)
  (transpose-lines 1)
  (forward-line -1)
  (indent-according-to-mode))
(defun duplicate-line()
  "Duplicates current line."
  (interactive)
  (move-beginning-of-line 1)
  (kill-line)
  (yank)
  (open-line 1)
  (next-line 1)
  (yank)
  )
(defun rename-file-and-buffer ()
  "Rename the current buffer and file it is visiting."
  (interactive)
  (let ((filename (buffer-file-name)))
    (if (not (and filename (file-exists-p filename)))
        (message "Buffer is not visiting a file!")
      (let ((new-name (read-file-name "New name: " filename)))
        (cond
         ((vc-backend filename) (vc-rename-file filename new-name))
         (t
          (rename-file filename new-name t)
          (set-visited-file-name new-name t t)))))))
(defun delete-file-and-buffer ()
  "Kill the current buffer and deletes the file it is visiting."
  (interactive)
  (let ((filename (buffer-file-name)))
    (when filename
      (if (vc-backend filename)
          (vc-delete-file filename)
        (progn
          (delete-file filename)
          (message "Deleted file %s" filename)
          (kill-buffer))))))
(defun my/enlarge-window-horizontally ()
  (interactive)
  (enlarge-window-horizontally 7))
(defun my/shrink-window-horizontally ()
  (interactive)
  (shrink-window-horizontally 7))
(defun my/enlarge-window ()
  (interactive)
  (enlarge-window 7))
(defun my/shrink-window ()
  (interactive)
  (shrink-window 7))
(defun split4 ()
  (interactive)
  (command-execute 'split-window-horizontally)
  (command-execute 'split-window-vertically)
  (command-execute 'other-window)
  (command-execute 'other-window)
  (command-execute 'split-window-vertically))

(global-set-key (kbd "C-<return>") 'insert-line-below)
(global-set-key (kbd "C-S-<return>") 'insert-line-above)
(global-set-key (kbd "C-<up>") 'move-line-up)
(global-set-key (kbd "C-<down>") 'move-line-down)
(global-set-key (kbd "C-S-d") 'duplicate-line)
(global-set-key (kbd "S-C-<left>") 'my/shrink-window-horizontally)
(global-set-key (kbd "S-C-<right>") 'my/enlarge-window-horizontally)
(global-set-key (kbd "S-C-<down>") 'my/shrink-window)
(global-set-key (kbd "S-C-<up>") 'my/enlarge-window)
(global-set-key (kbd "C-x C-r") 'rename-file-and-buffer)
(global-set-key (kbd "C-c D")  'delete-file-and-buffer)
